---
version: '3.4'
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
    
    volumes:
      - /root/shared/Compartida3/torrent/data:/config
      - /root/shared/Compartida3/torrent/downloads:/downloads
      - /root/shared/Compartida3/torrent/folder:/watch

    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    
    restart: always

